# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# Updated for grpcio >= 1.62
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import gpi_pb2 as gpi__pb2


class GPIStub(object):
    """The GPI service definition."""

    def __init__(self, channel):
        self.run = channel.unary_unary(
            '/GPI/run',
            request_serializer=gpi__pb2.Request.SerializeToString,
            response_deserializer=gpi__pb2.Result.FromString,
        )


class GPIServicer(object):
    """The GPI service definition."""

    def run(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


class _GPIGenericMethodHandler(grpc.GenericRpcHandler):
    """Generic RPC handler that routes calls to the GPI servicer."""

    def __init__(self, servicer):
        self._servicer = servicer
        self._handlers = {
            'run': grpc.unary_unary_rpc_method_handler(
                servicer.run,
                request_deserializer=gpi__pb2.Request.FromString,
                response_serializer=gpi__pb2.Result.SerializeToString,
            ),
        }

    def service_name(self):
        return 'GPI'

    def service(self, handler_call_details):
        method = handler_call_details.method.rpartition('/')[-1]
        return self._handlers.get(method)


def add_GPIServicer_to_server(servicer, server):
    server.add_generic_rpc_handlers((_GPIGenericMethodHandler(servicer),))


class GPI(object):
    """Experimental static call interface."""

    @staticmethod
    def run(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GPI/run',
            gpi__pb2.Request.SerializeToString,
            gpi__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
