"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
import sys
from setuptools import setup

# Define paths
HERE = os.path.abspath(__file__)
THISDIR = os.path.dirname(HERE)
GPIREPO = os.path.realpath(os.path.join(THISDIR, '..', 'lib', 'gpi'))
ICONFILE = os.path.join(GPIREPO, 'graphics', 'gpi.icns')

sys.path.append(GPIREPO)

APP = ['gpi_launch.py']
DATA_FILES = []
OPTIONS = {'packages' : ['PIL', 'PyQt5', 'qtpy', 'gpi', 'pyqtgraph', 'pathos', "autopep8", "matplotlib", "ctypes" ]}


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
